name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mypy:
    name: black & mypy
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
  - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements-dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: pip install -r requirements-dev.txt -r requirements-benchmarks.txt
    - name: Black & mypy
      run: |
        python -m black --check --diff .
        python -m mypy cropharvest process_labels test benchmarks
        python -m mypy benchmarks/dl
  test:
    runs-on: ${{ matrix.os }}
    env:
      MPLBACKEND: Agg
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        exclude:
        - os: windows-latest
          python-version: 3.6
    # defaults:
    #   run:
    #     shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # - name: Install apt dependencies (Linux)
      #   run: sudo apt-get install unrar
      #   if: ${{ runner.os == 'Linux' }}
    # - name: Install brew dependencies (macOS)
    #   run: brew install rar
      if: ${{ runner.os == 'macOS' }}
    - name: Install conda (Windows)
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
        channel-priority: strict
      if: ${{ runner.os == 'Windows' }}
    - name: Install conda dependencies (Windows)
      run: |
        conda install 'rasterio>=1.2.6'
        conda list
        conda info
      if: ${{ runner.os == 'Windows' }}
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: pip install -r requirements-dev.txt -r requirements-benchmarks.txt
      - name: Run tests
        run: |
          python -m pytest
